name: HeartAgeUtils
main: Color_yr.HeartAgeUtils.HeartAgeUtils
author: Color_yr
version: 1.0.0
api-version: 1.15

loadbefore: [vault]

softdepend: [vault]

commands:
  heartageutils:
    description: 插件主指令
    usage: §4[HeartAgeUtils]§6/heartageutils help来查看帮助
  hau:
    description: 插件主指令
    usage: §4[HeartAgeUtils]§6/heartageutils help来查看帮助