name: HeartAge_year
main: Color_yr.HeartAge_year.HeartAge_year
author: Color_yr
version: 1.0.0
api-version: 1.13

commands:
  heartage:
    description: 插件主指令
    usage: §4[HeartAge_year]§6/heartage help来查看帮助
  tpStone:
    description: 传送石指令
    usage: §4[HeartAge_year]§6/tpStone help来查看帮助